package com.gestionPeliculas.gestionPeliculas.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum Pais {
    AFGANISTAN("Afganistán"),
    ALBANIA("Albania"),
    ALEMANIA("Alemania"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANTIGUA_Y_BARBUDA("Antigua y Barbuda"),
    ARABIA_SAUDITA("Arabia Saudita"),
    ARGELIA("Argelia"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIAN("Azerbaiyán"),
    BAHAMAS("Bahamas"),
    BANGLADES("Bangladés"),
    BARBADOS("Barbados"),
    BAREIN("Baréin"),
    BELGICA("Bélgica"),
    BELICE("Belice"),
    BENIN("Benín"),
    BIELORRUSIA("Bielorrusia"),
    BIRMANIA_MYANMAR("Birmania/Myanmar"),
    BOLIVIA("Bolivia"),
    BOSNIA_Y_HERZEGOVINA("Bosnia y Herzegovina"),
    BOTSUANA("Botsuana"),
    BRASIL("Brasil"),
    BRUNEI("Brunéi"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    BUTAN("Bután"),
    CABO_VERDE("Cabo Verde"),
    CAMBOYA("Camboya"),
    CAMERUN("Camerún"),
    CANADA("Canadá"),
    CATAR("Catar"),
    CHAD("Chad"),
    CHILE("Chile"),
    CHINA("China"),
    CHIPRE("Chipre"),
    CIUDAD_DEL_VATICANO("Ciudad del Vaticano"),
    COLOMBIA("Colombia"),
    COMORAS("Comoras"),
    COREA_DEL_NORTE("Corea del Norte"),
    COREA_DEL_SUR("Corea del Sur"),
    COSTA_DE_MARFIL("Costa de Marfil"),
    COSTA_RICA("Costa Rica"),
    CROACIA("Croacia"),
    CUBA("Cuba"),
    DINAMARCA("Dinamarca"),
    DOMINICA("Dominica"),
    ECUADOR("Ecuador"),
    EGIPTO("Egipto"),
    EL_SALVADOR("El Salvador"),
    EMIRATOS_ARABES_UNIDOS("Emiratos Árabes Unidos"),
    ERITREA("Eritrea"),
    ESLOVAQUIA("Eslovaquia"),
    ESLOVENIA("Eslovenia"),
    ESPANA("España"),
    ESTADOS_UNIDOS("Estados Unidos"),
    ESTONIA("Estonia"),
    ETIOPIA("Etiopía"),
    FILIPINAS("Filipinas"),
    FINLANDIA("Finlandia"),
    FIJI("Fiyi"),
    FRANCIA("Francia"),
    GABON("Gabón"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GRANADA("Granada"),
    GRECIA("Grecia"),
    GUATEMALA("Guatemala"),
    GUYANA("Guyana"),
    GUINEA("Guinea"),
    GUINEA_ECUATORIAL("Guinea ecuatorial"),
    GUINEA_BISAU("Guinea-Bisáu"),
    HAITI("Haití"),
    HONDURAS("Honduras"),
    HUNGRIA("Hungría"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAK("Irak"),
    IRAN("Irán"),
    IRLANDA("Irlanda"),
    ISLANDIA("Islandia"),
    ISLAS_MARSHALL("Islas Marshall"),
    ISLAS_SALOMON("Islas Salomón"),
    ISRAEL("Israel"),
    ITALIA("Italia"),
    JAMAICA("Jamaica"),
    JAPON("Japón"),
    JORDANIA("Jordania"),
    KAZAJISTAN("Kazajistán"),
    KENIA("Kenia"),
    KIRGUISTAN("Kirguistán"),
    KIRIBATI("Kiribati"),
    KUWAIT("Kuwait"),
    LAOS("Laos"),
    LESOTO("Lesoto"),
    LETONIA("Letonia"),
    LIBANO("Líbano"),
    LIBERIA("Liberia"),
    LIBIA("Libia"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIA("Lituania"),
    LUXEMBURGO("Luxemburgo"),
    MACEDONIA_DEL_NORTE("Macedonia del Norte"),
    MADAGASCAR("Madagascar"),
    MALASIA("Malasia"),
    MALAWI("Malaui"),
    MALDIVAS("Maldivas"),
    MALI("Malí"),
    MALTA("Malta"),
    MARRUECOS("Marruecos"),
    MAURICIO("Mauricio"),
    MAURITANIA("Mauritania"),
    MEXICO("México"),
    MICRONESIA("Micronesia"),
    MOLDAVIA("Moldavia"),
    MONACO("Mónaco"),
    MONGOLIA("Mongolia"),
    MONTENEGRO("Montenegro"),
    MOZAMBIQUE("Mozambique"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NICARAGUA("Nicaragua"),
    NIGER("Níger"),
    NIGERIA("Nigeria"),
    NORUEGA("Noruega"),
    NUEVA_ZELANDA("Nueva Zelanda"),
    OMAN("Omán"),
    PAISES_BAJOS("Países Bajos"),
    PAKISTAN("Pakistán"),
    PALAOS("Palaos"),
    PANAMA("Panamá"),
    PAPUA_NUEVA_GUINEA("Papúa Nueva Guinea"),
    PARAGUAY("Paraguay"),
    PERU("Perú"),
    POLONIA("Polonia"),
    PORTUGAL("Portugal"),
    REINO_UNIDO("Reino Unido"),
    REP_CENTROAFRICANA("República Centroafricana"),
    REP_CHECA("República Checa"),
    REP_DEL_CONGO("República del Congo"),
    REP_DEMOCRATICA_DEL_CONGO("República Democrática del Congo"),
    REP_DOMINICANA("República Dominicana"),
    REP_SUDAFRICANA("República Sudafricana"),
    RUANDA("Ruanda"),
    RUMANIA("Rumanía"),
    RUSIA("Rusia"),
    SAMOA("Samoa"),
    SAN_CRISTOBAL_Y_NIEVES("San Cristóbal y Nieves"),
    SAN_MARINO("San Marino"),
    SAN_VINCENTE_Y_GRANADINAS("San Vicente y las Granadinas"),
    SANTA_LUCIA("Santa Lucía"),
    SANTO_TOME_Y_PRINCIPE("Santo Tomé y Príncipe"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONA("Sierra Leona"),
    SINGAPUR("Singapur"),
    SIRIA("Siria"),
    SOMALIA("Somalia"),
    SRI_LANKA("Sri Lanka"),
    SUAZILANDIA("Suazilandia"),
    SUDAN("Sudán"),
    SUDAN_DEL_SUR("Sudán del Sur"),
    SUECIA("Suecia"),
    SUIZA("Suiza"),
    SURINAM("Surinam"),
    TAILANDIA("Tailandia"),
    TANZANIA("Tanzania"),
    TAYIKISTAN("Tayikistán"),
    TIMOR_ORIENTAL("Timor Oriental"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_Y_TOBAGO("Trinidad y Tobago"),
    TUNEZ("Túnez"),
    TURKMENISTAN("Turkmenistán"),
    TURQUIA("Turquía"),
    TUVALU("Tuvalu"),
    UCRANIA("Ucrania"),
    UGANDA("Uganda"),
    URUGUAY("Uruguay"),
    UZBEKISTAN("Uzbekistán"),
    VANUATU("Vanuatu"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    YEMEN("Yemen"),
    YIBUTI("Yibuti"),
    ZAMBIA("Zambia"),
    ZIMBABUE("Zimbabue");

    private final String nombre;


    @JsonValue
    public String getNombre() {
        return nombre;
    }

    @JsonCreator
    public static Pais fromNombre(String nombre) {
        for (Pais p : Pais.values()) {
            if (p.nombre.equalsIgnoreCase(nombre)) {
                return p;
            }
        }
        throw new IllegalArgumentException("País no válido: " + nombre);
    }
}

